version: '3.7'

volumes:
  prometheus_volume:
  grafana_volume:
  mosquitto_data:
  mosquitto_logs:

services:
  # local mqtt server
  mosquitto:
    image: eclipse-mosquitto:2
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "1884:1884"
    volumes:
      - "./mosquitto.conf:/mosquitto/config/mosquitto.conf"
      - "mosquitto_data:/mosquitto/data"
      - "mosquitto_logs:/mosquitto/log"


