version: '3.7'


volumes:
  prometheus_volume:
  grafana_volume:

services:
  # local mqtt server
  mosquitto:
    image: eclipse-mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "1884:1884"
    volumes:
      - "./data/mosquitto/config:/mosquitto/config"
      - "./data/mosquitto/data:/mosquitto/data"
      - "./data/mosquitto/log:/mosquitto/log"
    environment:
      TZ: "${TIMEZONE}"
    user: "${LOCAL_USER}:${LOCAL_USER}"


